- hosts: webservers
  vars: 
    Allstate: false
    machine_type: mac
    users:
      ansible:
        name: ansible_cm
        telephone: 123-456-7890
      puppet:
        name: puppet_cm
        telephone: 987-654-3210
  gather_facts: true
  tasks:
  #- import_tasks: loops/std_loop.yml
  - import_tasks: loops/inventory_loops.yml
