##Playbook Conditionals
---
- hosts: dbservers
  vars:
     mail_services:
        - postfix
        - dovecot
     alpha: [ 'a', 'b', 'c', 'd', 'e']
     numbers: [ 1, 2, 3, 4 ]
  tasks:
  - name: Install postfix
    yum: 
       name: postfix
       state: latest
    tags:
      - normal
  - name: Install dovecot
    yum: 
       name: dovecot
       state: latest
    tags:
      - normal

  - name: Install packages using with_items loop
    yum:
       name: "{{ item }}"
       state: latest
    with_items:
       - postfix
       - dovecot
    tags:
      - withitems

  - name: Install packages using loop and variables
    yum:
       name: "{{ item }}"
       state: latest
    with_items: "{{ mail_services }}"

  - name: Print Hello to Jonathan
    debug:
      msg: " Hello Jonathan"
    tags:
     - always 
