- hosts: webservers[0]
  vars_prompt:
    - name: "pkg_name"
      prompt: "What Package you wanna install?"
      private: no
  tasks:
  - name: Install a {{pkg_name}}
    yum: 
      name: "{{pkg_name}}"
    register: pkg_name_result

  - name: Show me the pkg_name_result value
    debug:
     var: pkg_name_result.results
