- name: Task vars example
  hosts: webservers[0]
  vars_files:
    - copyvars
  tasks:
  - name: Copy hosts file to /tmp directory
    copy: 
      src: "{{SOURCE}}"
      dest: "{{DESTINATION}}"
    vars:
     SOURCE: /etc/ansible/hosts
     DESTINATION: /tmp/
