- hosts: webservers[0]
  vars_prompt:
    - name: "pkg_name"
      prompt: "What Package you wanna install?"
      private: yes
  tasks:
  - name: Install a {{pkg_name}}
    yum: 
      name: "{{pkg_name}}"

